export const HARD_CODED_DATA = [
  {
    id: '1',
    name: 'Amine Deghmine',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
    prints: 'Ipsum Dolor',
  },
  {
    id: '2',
    name: 'Amine Deghmine',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
    prints: 'Ipsum Dolor',
  },
  {
    id: '3',
    name: 'Amine Deghmine',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
    prints: 'Ipsum Dolor',
  },
]
